### ISSUE TITLE
Is future-fstrings compatible with Python 3.6?

### ISSUE THREAD

**Issue by radek-sprta** [asottile/future-fstrings#11]
Hello,
I wanted to add support for Python < 3.6 for my package by using future-fstrings. However, when trying to run the program in Python 3.6, I get:

SyntaxError: unknown encoding: future_fstrings

Am I doing something wrong, or does future-fstrings only work on Python < 3.6?

**Comment by asottile** [comment]
It should work, did you install it? (node that our tests also run against py36)

**Comment by radek-sprta** [comment]
So I guess something went awry with my installation of future-fstrings. I got the syntax error even when running the future-fstrings test suite, which was really weird. So I reinstalled future-fstrings and everything works as expected now. Sorry for taking your time!

**Comment by asottile** [comment]
No problem :)

**Comment by asottile** [comment]
Yep!

https://github.com/asottile/future-fstrings/blob/83a7d57f90b4faed9135967c09da0f15d4ee8ec9/future_fstrings.py#L254-L265
