### ISSUE TITLE
Distrubution via Anaconda?

### ISSUE THREAD

**Issue by sterlingbaldwin** [asottile/future-fstrings#17]
Hey, I really like this package and would like to use it in a project that Im distributing via anaconda. Would it be possible for you to do a conda build so it can be included as a dependency? 

If you don't want to do the work, would it be OK if I build it and distribute it through my channel? I wouldn't change anything except to add the meta.yaml required by anaconda.

This package is great and I'm sure other conda users would appreciate being able to include it!

**Comment by asottile** [comment]
Personally I have no interest in contributing / maintaining anything for conda.  If you'd like to set up the necessary stuff for it then go for it 👍

**Comment by asottile** [comment]
Seems you can follow https://github.com/conda-forge/staged-recipes to get started?

**Comment by sterlingbaldwin** [comment]
Im fairly familiar with conda, and will submit this to conda-forge. I know this is MIT licensed, but I wanted to make sure you were cool with it being distributed via conda, and I'll make sure you're properly attributed.

**Comment by asottile** [comment]
sounds good to me :) go for it!

**Comment by asottile** [comment]
@sterlingbaldwin any progress on this?

**Comment by sterlingbaldwin** [comment]
See: https://github.com/sterlingbaldwin/staged-recipes/blob/master/recipes/future-fstrings/meta.yaml

**Comment by sterlingbaldwin** [comment]
I still need to add the test section and submit the PR.

**Comment by sterlingbaldwin** [comment]
Started the PR, first round of tests from the conda-forge-linter are passing.

https://github.com/conda-forge/staged-recipes/pull/6154#issuecomment-399547496

**Comment by asottile** [comment]
neat! this just merged: https://github.com/conda-forge/future_fstrings-feedstock

**Comment by sterlingbaldwin** [comment]
Ci systems are weird. Looks like closing and re-opening the issue was enough to get travis to pass.
