### ISSUE TITLE
Linter is crashing

### ISSUE THREAD

**Issue by Vi-Sri** [asottile/future-fstrings#22]
As i replaced the UTF-8 cookie the flake8 linter crashed in atom. Any one having any fix for this ?

**Comment by asottile** [comment]
I'm not sure I understand, could you provide a reproduction?

**Comment by Vi-Sri** [comment]
Upon placing this
  
# -*- coding: future_fstrings -*-

The Flake8 Linter in Atom editor is crashing.  I am not able to reproduce the results now. Hence ill close the issue.
