### ISSUE TITLE
Why is this not in the __future__ library!!!

### ISSUE THREAD

**Issue by davehowell** [asottile/future-fstrings#25]
This library made my day

**Comment by asottile** [comment]
hah I actually had an idea on how to make it work with "custom" `__future__` imports, something like this:

```python
# -*- coding: pyrewrite -*-
from __future__ import fstrings
...
```

and then `pyrewrite` would be a package which registers a bunch of different source rewriters (similar to how `babel` is in javascript-land)

but most of that idea was after this already worked and I didn't really have any other source-rewriting ideas at the time 🤷‍♂️ 

if you found this useful / amusing / interesting you might also find [future-breakpoint](https://github.com/asottile/future-breakpoint) interesting as well!

Thanks for the issue :)
