### ISSUE TITLE
CLI does not change input

### ISSUE THREAD

**Issue by chlandsi** [asottile/future-fstrings#28]
When I run `future-fstrings-show` on a sample file like the one in the description with Python 3.7.1, the output is the unchanged content of the file. I would expect to see the replacements. Running code through the codec works fine on other python versions though.

**Comment by asottile** [comment]
The codec is a noop in versions which natively support f-strings. So I think this is expected. What is your use case?

**Comment by chlandsi** [comment]
Ok, then I understand. I have some code that uses f-strings and I want to convert it to `.format(...)` notation for a deployment where I don't want to install a codec, and I don't want to do the conversion manually. So I could just run it on an older python, and it would work; but this might be a valid usecase for this tool.

**Comment by asottile** [comment]
Ah that makes sense, I think I could add an option that tries the rewrite in 3.6+ maybe? The problem is it won't have the rewriting dependencies necessarily because they only get installed when needed

**Comment by chlandsi** [comment]
That would be great...

**Comment by asottile** [comment]
@chlandsi would you like to take a stab at it?

- the [cli code is here](https://github.com/asottile/future-fstrings/blob/8dcf6514290f7e1b31edd33cdeb7f596304f8325/future_fstrings.py#L287-L294)
- you'll probably need to do something to keep [this symbol](https://github.com/asottile/future-fstrings/blob/8dcf6514290f7e1b31edd33cdeb7f596304f8325/future_fstrings.py#L263) around and not clobbered

**Comment by chlandsi** [comment]
Thanks for the pointers, I will have a look.

**Comment by asottile** [comment]
If you `pip install future-fstrings[rewrite]>=1.1.0` you can now use `future-fstrings-show` to rewrite code even when running in a modern python!
