### ISSUE TITLE
Does not work in docstring position

### ISSUE THREAD

**Issue by flying-sheep** [asottile/future-fstrings#29]
Normal f-strings work when put as docstrings.

However this codec rewrites them to expressions, which aren’t automatically assigned to `thing.__doc__` when in a docstring position (first item in a function/class).

To fully support f-strings, this package should transform e.g.

```py
def foo():
    f"""Hai
    {thar}
    """
    pass
```

to

```py
def foo():
    pass

foo.__doc__ = textwrap.dedent(
    """Hai
    {}
    """.format(thar)
)
```

(Or so, I didn’t check if `dedent` really does what we think it does)

**Comment by asottile** [comment]
the dedent is incorrect / unnecessary, but otherwise you're correct -- are you willing to try a stab at this? shouldn't be too difficult

**Comment by flying-sheep** [comment]
I have quite a bit on my plate, so I can’t say if I will find the time. Probably not anytime soon, sorry :cry:

**Comment by asottile** [comment]
that's fine, it's a pretty severe edge case that shouldn't really impact execution anyway :man_shrugging: -- if someone's depending on that they're already broken by `python -0`

**Comment by flying-sheep** [comment]
Interesting, could you please elaborate? How does `-O` come into play here?

**Comment by asottile** [comment]
err, I guess I mean `-OO`

```
def f():
    """doc"""

print(f.__doc__)
```

```
$ python t.py
doc
$ python -OO t.py
None
```

**Comment by flying-sheep** [comment]
Ah I see. Well, I don’t think anyone is depending on that in the sense that their application breaks once the docstrings are gone, but e.g. Sphinx of course relies on them!

**Comment by asottile** [comment]
usually it's a good idea to generate docs from the latest supported python version anyway so that's probably not an issue either

**Comment by flying-sheep** [comment]
True! But at the moment readthedocs uses 3.5 by default still.

**Comment by asottile** [comment]
actually, are you sure f-strings are valid docstrings?

```
$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> def f():
...     f'{f.__name__} hello world'
... 
>>> f.__doc__
>>> 
```

**Comment by asottile** [comment]
actually, are you sure f-strings are valid docstrings?

```
$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> def f():
...     f'{f.__name__} hello world'
... 
>>> f.__doc__
>>> 
```

**Comment by asottile** [comment]
actually this issue is invalid, I should have checked :laughing: 

https://docs.python.org/3/reference/lexical_analysis.html#formatted-string-literals

> Formatted string literals cannot be used as docstrings, even if they do not include expressions.

**Comment by flying-sheep** [comment]
That’s a lie, it works fine!

**Comment by asottile** [comment]
show me! what version are you using?

**Comment by flying-sheep** [comment]
hm, this implies that it never worked: https://bugs.python.org/issue28739

probably I’m just wrong…

**Comment by asottile** [comment]
looks like in 3.6.0 it "worked" for f-string-docstrings without expressions:

```
root@673f92e13a74:/# python3.6
Python 3.6.0 (default, Feb 28 2017, 22:20:46) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> def f():
...    f'''hi'''
... 
>>> f.__doc__
'hi'
>>> def f():
...     f'{f.__name__} hi'
... 
>>> f.__doc__
```

This was removed in 3.6.1:

```
/ # python
Python 3.6.1 (default, Jun 28 2017, 21:57:03) 
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> def f():
...    f'''hi'''
... 
>>> f.__doc__
>>> 
```

here's the relevant bpo issue: https://bugs.python.org/issue28739
