### ISSUE TITLE
New python3.8 debug f-strings

### ISSUE THREAD

**Issue by asottile** [asottile/future-fstrings#40]
https://github.com/python/cpython/pull/13123

**Comment by asottile** [comment]
I don't think I'll implement this

**Comment by pmp-p** [comment]
a bit sad but very comprehensible, not sure it will be widely used even for few years to come

**Comment by asottile** [comment]
it's easy to implement, but it's unclear how to turn it on in any reasonable way in python3.6 - python3.7

and it's way less of a value add than f-strings are alone 🤷‍♂ 

that said, if someone wants to pick this up, by all means 👍

**Comment by pmp-p** [comment]
3.6/3.7 indeed dit not think of that, but if it is "easy" as most Python vm target only 3.4/3.5 it still could be very usefull ( eg micropython/rustpython target 3.4, voc from beeware and other transpilers could use the cli ).

Also one can imagine if an os is recent enough to have 3.6/3.7, then that missing support is a push argument to go 3.8.

**Comment by asottile** [comment]
yeah the problem is you'd never live in a world where you'd target 3.4 + 3.5 + 3.8 but not 3.6 + 3.7 so I just don't see the usefulness there
