### ISSUE TITLE
Inclusion in setup.py?

### ISSUE THREAD

**Issue by stringhamc** [asottile/future-fstrings#42]
I love how easy it is to convert code written using fstrings to pre 3.6 compatible string formatting, but I'd like to keep using fstrings and not have to have all users of my package install future-fstrings and I add the encoding to the top of the file.... So I'm wondering if there is a way to incorporate this into the build process of my setup.py such that it would run `future-fstrings-show code.py > code.py` on all the files if it were run on python <3.6.. any ideas?

**Comment by asottile** [comment]
here's a demo, feel free to turn it into something real and/or a PR which makes this easier:

```python
# ==> foomod.py <==
thing = 'world'
print(f'hello {thing}')
```

```python
# ==> foopkg/__init__.py <==
```

```python
# ==> foopkg/mod.py <==
thing = 'world'
print(f'hello {thing}')
```

```python
# ==> setup.py <==
from setuptools import setup
from setuptools.command.build_py import build_py


class fstrings_build_py(build_py):
    def run(self):
        import future_fstrings

        for _, _, filename in self.find_all_modules():
            with open(filename, 'rb') as f:
                contents, _ = future_fstrings.decode(f.read())
            with open(filename, 'wb') as f:
                f.write(contents.encode('UTF-8'))

        build_py.run(self)

setup(
    name='foo',
    packages=['foopkg'],
    py_modules=['foomod'],
    setup_requires=['future-fstrings'],
    cmdclass={'build_py': fstrings_build_py},
)
```

```console
$ pip install ../
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Processing /tmp/x
Building wheels for collected packages: foo
  Building wheel for foo (setup.py) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-efyuhx/wheels/13/0c/3a/6ada8afffd8f1dc971356cd7401875dbfd151327357e0e9949
Successfully built foo
Installing collected packages: foo
Successfully installed foo-0.0.0
$ python -m foomod
hello world
$ python -m foopkg.mod
hello world
```

**Comment by stringhamc** [comment]
This is awesome thanks!

**Comment by jordan-heemskerk** [comment]
@asottile Would you be open to including an implementation of the `fstrings_build_py` in `future-fstrings`?

The example above would then become something like
```python
from setuptools import setup
from future_fstrings.setuptools_ext import fstrings_build_py

setup(
    name='foo',
    packages=['foopkg'],
    py_modules=['foomod'],
    setup_requires=['future-fstrings'],
    cmdclass={'build_py': fstrings_build_py},
)
```

I'm happy to PR if you're open to it.

**Comment by asottile** [comment]
as written that wouldn't ~quite work (`setup_requires` is too late in that case since `future_fstrings` is imported at the module scope) -- you'd probably do it something like this:

https://github.com/asottile/setuptools-golang#usage

where `future-fstrings` would provide a distutils keyword: https://github.com/asottile/setuptools-golang/blob/a4951e05efc0cf6b9df42a6ff63ac45e0b7b664d/setup.cfg#L32

and then use it to modify the kwargs as needed:

https://github.com/asottile/setuptools-golang/blob/a4951e05efc0cf6b9df42a6ff63ac45e0b7b664d/setuptools_golang.py#L143-L146

(of course, being careful to avoid importing `setuptools` at the module scope inside the `future_fstrings` module since it's very expensive)

**Comment by asottile** [comment]
but sure, if you want to implement something like that, there's the template basically: ^
