### ISSUE TITLE
How to use fstrings from py 2.7 shell?

### ISSUE THREAD

**Issue by collinsethans** [asottile/future-fstrings#43]
I am using python 2.7.x and have installed future-fstrings. It works when I run a py script using it. However, I don't find a way to use it from the shell. Can you tell the method to do so?

Also, instead of using:

    # -*- coding: future_fstrings -*-

Is there an associated `__future__` import?

**Comment by asottile** [comment]
you can't, it only works for files

**Comment by collinsethans** [comment]
Instead of using:

    # -*- coding: future_fstrings -*-

Is there an associated __future__ import?

**Comment by asottile** [comment]
there is not, please see the README for the full documentation

**Comment by mickeyperlstein** [comment]
do you mean there is no way to run it from the ide? (i use pycharm, vscode and jupyter)

**Comment by asottile** [comment]
> it only works for files

**Comment by jschwartzentruber** [comment]
works for me ..
```
$ PYTHONIOENCODING=future_fstrings python2
Python 2.7.17 (default, Oct 22 2019, 09:14:09)
[GCC 9.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> a=123
>>> f"{a}"
'123'
>>> 
```

**Comment by asottile** [comment]
neat! hadn't even considered that :+1:
