### ISSUE TITLE
doesn't work in jupyternotebook.

### ISSUE THREAD

**Issue by potoo0** [asottile/future-fstrings#44]
doesn't work in jupyternotebook...

**Comment by asottile** [comment]
do you have a reproduction?

**Comment by potoo0** [comment]
- python : 3.5.3
- jupyter lab: 0.35.4
- future-fstrings: 1.2.0

run this will raise a SyntaxError in jupyter cell:
```python
# -*- coding: future_fstrings -*-

temp = 123
f"ss {temp}"
```
output:
```
  File "<ipython-input-2-33208a0e1fc4>", line 4
    f"ss {temp}"
               ^
SyntaxError: invalid syntax
```

Screenshot:
![image](https://user-images.githubusercontent.com/34411681/60225940-93f31b00-98bb-11e9-99ae-c9508978abd2.png)

**Comment by asottile** [comment]
See #43

**Comment by potoo0** [comment]
OK, thanks.

**Comment by asottile** [comment]
No problem! Probably could hook into jupyter somehow to pre-process the inputs, however I know very little about how that works :S

**Comment by potoo0** [comment]
Thank for your guide. I'll dig in.
