### ISSUE TITLE
Doesn't work after module docstring

### ISSUE THREAD

**Issue by penguindustin** [asottile/future-fstrings#45]
First of all, Great module! This saved me a ton of time in backporting from 3.6 to 3.5. One thing that would be great would be the ability to add the encoding cookie after things like a module docstring like so:

```
""" main.py
    Some module docstring text
"""
# -*- coding: future_fstrings -*-
```

I can also take a crack at it if not many other people are interested in this feature and are open to contributions.

**Comment by asottile** [comment]
Please familiarize yourself with [PEP 263](https://www.python.org/dev/peps/pep-0263/)

**Comment by penguindustin** [comment]
Thanks for the reference to the PEP, didn't know it was a feature of Python itself.

**Comment by asottile** [comment]
yeah, I'm (ab)using the source encoding directive -- if you want a more in-depth explanation of how everything ticks I recorded a video: https://www.youtube.com/watch?v=00h6aKnAdyY
