### ISSUE TITLE
does not work in jupyter-notebook

### ISSUE THREAD

**Issue by mickeyperlstein** [asottile/future-fstrings#46]
created a very simple setup

virtualenv for 2.7
pip install jupyter-notebook
pip install future-fstring

jupter-notebook

[1]:  # -*- coding: future_fstrings -*-
       import future_fstrings
[2] thing = 'world'
      print(f'hello {thing}')

errors

**Comment by asottile** [comment]
please search the issue tracker next time #44 #43

**Comment by mickeyperlstein** [comment]
In [1]:  # -- coding: future_fstrings --
   ...: import future_fstrings

In [2]: x = 'hello'

In [3]: f'{x}'
  File "<ipython-input-3-244aa22706bc>", line 1
    f'{x}'
         ^
SyntaxError: invalid syntax

**Comment by asottile** [comment]
read the issues my dude, I don't know what to tell ya <3
