### ISSUE TITLE
Encoding problem with python 2.7

### ISSUE THREAD

**Issue by shwetha-manvinkurke** [asottile/future-fstrings#48]
I am not sure why but I am unable to use this module because of the error- "SyntaxError: encoding problem: future_fstrings. I have python 2.7 on my machine.

**Comment by asottile** [comment]
How did you install `future-fstrings`? can you provide more information (your file contents, etc.)

**Comment by shwetha-manvinkurke** [comment]
I did a pip install. 

[FstringTest.txt](https://github.com/asottile/future-fstrings/files/3493427/FstringTest.txt)

![image](https://user-images.githubusercontent.com/6811347/62880671-c5486e80-bce2-11e9-8a50-718a6252882d.png)

**Comment by asottile** [comment]
Can you `python -m pip freeze --all`?

**Comment by shwetha-manvinkurke** [comment]
Alright got it working. Thanks for the help.

**Comment by asottile** [comment]
what was your solution?
