### ISSUE TITLE
Is it possible to optionally require future-fstrings?

### ISSUE THREAD

**Issue by kunaltyagi** [asottile/future-fstrings#56]
This dependency isn't needed for Python versions that ship with fstring support. Is it possible to change the "codec" in some manner so that missing `future-fstrings` isn't an error on those versions?

**Comment by asottile** [comment]
it [already does that](https://github.com/asottile/future-fstrings/blob/b7cc3ab961fa808c9f4a2e4cf075d811673467da/future_fstrings.py#L259-L264)

**Comment by asottile** [comment]
and no it's not possible if you're reuqesting a way to optionally use the encoding cookie, though you could consider preprocessing your source

**Comment by kunaltyagi** [comment]
Thanks for the quick response. Looks like I need to pre-process the source files.
