### ISSUE TITLE
Does not work with eval/exec

### ISSUE THREAD

**Issue by wimglenn** [asottile/future-fstrings#58]
```
# -*- coding: future_fstrings -*-
exec('f"1"')
```

a `SyntaxError` is raised

**Comment by asottile** [comment]
try `exec(b'f"1"'.decode('future-fstrings'))` -- there's not really anything that can be done with exec/eval otherwise

**Comment by wimglenn** [comment]
Why not? If you can rewrite the source code in the first place then you can rewrite the source code inside eval/exec too, no?

**Comment by asottile** [comment]
not without solving the halting problem
